name: beach_circle_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  mapbox_maps_flutter: ^2.12.0

  #Resource page Packages
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0 #For the url links add this
  font_awesome_flutter: ^10.7.0

  # Firebase packages
  firebase_core: ^3.15.2
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0


  #Weather Packages
  http: ^1.6.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/weather/

# flutter:
#   assets:
#     - assets/.env/.env.public.dev
